
/*
 * generated by Xtext
 */
 
package no.hal.scxml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class ScxmlxtExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return no.hal.scxml.ui.internal.ScxmlxtActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return no.hal.scxml.ui.internal.ScxmlxtActivator.getInstance().getInjector("no.hal.scxml.Scxmlxt");
	}
	
}
