/*
 * generated by Xtext
 */
package no.hal.scxml.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class ScxmlxtScopeProvider extends AbstractDeclarativeScopeProvider {
}
