/*
 * generated by Xtext
 */
package no.hal.scxml;

import no.hal.scxml.generator.ScxmlxtTerminalConverters;
import no.hal.scxml.scoping.ScxmlxtQualifiedNameProvider;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ScxmlxtRuntimeModule extends no.hal.scxml.AbstractScxmlxtRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
	  return ScxmlxtTerminalConverters.class;
	}

	@Override
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return ScxmlxtQualifiedNameProvider.class;
	}
}
