/*
* generated by Xtext
*/
package no.hal.scxml.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ScxmlxtAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("no/hal/scxml/parser/antlr/internal/InternalScxmlxt.tokens");
	}
}
