/*
 * generated by Xtext
 */
package no.hal.scxml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ScxmlxtUiModule extends no.hal.scxml.ui.AbstractScxmlxtUiModule {
	public ScxmlxtUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
