/*
* generated by Xtext
*/

package no.hal.scxml.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class ScxmlxtGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class StateMachineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StateMachine");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cImportsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cImportsResourceImportParserRuleCall_0_0 = (RuleCall)cImportsAssignment_0.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cStatesAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cStatesStateParserRuleCall_1_0_0 = (RuleCall)cStatesAssignment_1_0.eContents().get(0);
		private final Assignment cTransitionsAssignment_1_1 = (Assignment)cAlternatives_1.eContents().get(1);
		private final RuleCall cTransitionsAbstractTransitionParserRuleCall_1_1_0 = (RuleCall)cTransitionsAssignment_1_1.eContents().get(0);
		private final Assignment cVariablesAssignment_1_2 = (Assignment)cAlternatives_1.eContents().get(2);
		private final RuleCall cVariablesVarDefParserRuleCall_1_2_0 = (RuleCall)cVariablesAssignment_1_2.eContents().get(0);
		
		//StateMachine:
		//	imports+=ResourceImport* (states+=State | transitions+=AbstractTransition | variables+=VarDef)*;
		public ParserRule getRule() { return rule; }

		//imports+=ResourceImport* (states+=State | transitions+=AbstractTransition | variables+=VarDef)*
		public Group getGroup() { return cGroup; }

		//imports+=ResourceImport*
		public Assignment getImportsAssignment_0() { return cImportsAssignment_0; }

		//ResourceImport
		public RuleCall getImportsResourceImportParserRuleCall_0_0() { return cImportsResourceImportParserRuleCall_0_0; }

		//(states+=State | transitions+=AbstractTransition | variables+=VarDef)*
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//states+=State
		public Assignment getStatesAssignment_1_0() { return cStatesAssignment_1_0; }

		//State
		public RuleCall getStatesStateParserRuleCall_1_0_0() { return cStatesStateParserRuleCall_1_0_0; }

		//transitions+=AbstractTransition
		public Assignment getTransitionsAssignment_1_1() { return cTransitionsAssignment_1_1; }

		//AbstractTransition
		public RuleCall getTransitionsAbstractTransitionParserRuleCall_1_1_0() { return cTransitionsAbstractTransitionParserRuleCall_1_1_0; }

		//variables+=VarDef
		public Assignment getVariablesAssignment_1_2() { return cVariablesAssignment_1_2; }

		//VarDef
		public RuleCall getVariablesVarDefParserRuleCall_1_2_0() { return cVariablesVarDefParserRuleCall_1_2_0; }
	}

	public class ResourceImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ResourceImport");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDomainModelImportParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDomainDataImportParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ResourceImport:
		//	DomainModelImport | DomainDataImport;
		public ParserRule getRule() { return rule; }

		//DomainModelImport | DomainDataImport
		public Alternatives getAlternatives() { return cAlternatives; }

		//DomainModelImport
		public RuleCall getDomainModelImportParserRuleCall_0() { return cDomainModelImportParserRuleCall_0; }

		//DomainDataImport
		public RuleCall getDomainDataImportParserRuleCall_1() { return cDomainDataImportParserRuleCall_1; }
	}

	public class DomainModelImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DomainModelImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDomainKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cImportURIAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cImportURISTRINGTerminalRuleCall_2_0 = (RuleCall)cImportURIAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//DomainModelImport:
		//	"domain"? "model" importURI=STRING ";";
		public ParserRule getRule() { return rule; }

		//"domain"? "model" importURI=STRING ";"
		public Group getGroup() { return cGroup; }

		//"domain"?
		public Keyword getDomainKeyword_0() { return cDomainKeyword_0; }

		//"model"
		public Keyword getModelKeyword_1() { return cModelKeyword_1; }

		//importURI=STRING
		public Assignment getImportURIAssignment_2() { return cImportURIAssignment_2; }

		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_2_0() { return cImportURISTRINGTerminalRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class DomainDataImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DomainDataImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDomainKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cDataKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cImportURIAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cImportURISTRINGTerminalRuleCall_2_0 = (RuleCall)cImportURIAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//DomainDataImport:
		//	"domain"? "data" importURI=STRING ";";
		public ParserRule getRule() { return rule; }

		//"domain"? "data" importURI=STRING ";"
		public Group getGroup() { return cGroup; }

		//"domain"?
		public Keyword getDomainKeyword_0() { return cDomainKeyword_0; }

		//"data"
		public Keyword getDataKeyword_1() { return cDataKeyword_1; }

		//importURI=STRING
		public Assignment getImportURIAssignment_2() { return cImportURIAssignment_2; }

		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_2_0() { return cImportURISTRINGTerminalRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cInitialTransitionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cInitialTransitionInitialTransitionParserRuleCall_0_0 = (RuleCall)cInitialTransitionAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Keyword cSemicolonKeyword_2_0 = (Keyword)cAlternatives_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cAlternatives_2.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Alternatives cAlternatives_2_1_1 = (Alternatives)cGroup_2_1.eContents().get(1);
		private final Assignment cStatesAssignment_2_1_1_0 = (Assignment)cAlternatives_2_1_1.eContents().get(0);
		private final RuleCall cStatesStateParserRuleCall_2_1_1_0_0 = (RuleCall)cStatesAssignment_2_1_1_0.eContents().get(0);
		private final Assignment cTransitionsAssignment_2_1_1_1 = (Assignment)cAlternatives_2_1_1.eContents().get(1);
		private final RuleCall cTransitionsAbstractTransitionParserRuleCall_2_1_1_1_0 = (RuleCall)cTransitionsAssignment_2_1_1_1.eContents().get(0);
		private final Assignment cVariablesAssignment_2_1_1_2 = (Assignment)cAlternatives_2_1_1.eContents().get(2);
		private final RuleCall cVariablesVarDefParserRuleCall_2_1_1_2_0 = (RuleCall)cVariablesAssignment_2_1_1_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_1_2 = (Keyword)cGroup_2_1.eContents().get(2);
		
		//State:
		//	initialTransition=InitialTransition? name=ID (";" | "{" (states+=State | transitions+=AbstractTransition |
		//	variables+=VarDef)* "}");
		public ParserRule getRule() { return rule; }

		//initialTransition=InitialTransition? name=ID (";" | "{" (states+=State | transitions+=AbstractTransition |
		//variables+=VarDef)* "}")
		public Group getGroup() { return cGroup; }

		//initialTransition=InitialTransition?
		public Assignment getInitialTransitionAssignment_0() { return cInitialTransitionAssignment_0; }

		//InitialTransition
		public RuleCall getInitialTransitionInitialTransitionParserRuleCall_0_0() { return cInitialTransitionInitialTransitionParserRuleCall_0_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//";" | "{" (states+=State | transitions+=AbstractTransition | variables+=VarDef)* "}"
		public Alternatives getAlternatives_2() { return cAlternatives_2; }

		//";"
		public Keyword getSemicolonKeyword_2_0() { return cSemicolonKeyword_2_0; }

		//"{" (states+=State | transitions+=AbstractTransition | variables+=VarDef)* "}"
		public Group getGroup_2_1() { return cGroup_2_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2_1_0() { return cLeftCurlyBracketKeyword_2_1_0; }

		//(states+=State | transitions+=AbstractTransition | variables+=VarDef)*
		public Alternatives getAlternatives_2_1_1() { return cAlternatives_2_1_1; }

		//states+=State
		public Assignment getStatesAssignment_2_1_1_0() { return cStatesAssignment_2_1_1_0; }

		//State
		public RuleCall getStatesStateParserRuleCall_2_1_1_0_0() { return cStatesStateParserRuleCall_2_1_1_0_0; }

		//transitions+=AbstractTransition
		public Assignment getTransitionsAssignment_2_1_1_1() { return cTransitionsAssignment_2_1_1_1; }

		//AbstractTransition
		public RuleCall getTransitionsAbstractTransitionParserRuleCall_2_1_1_1_0() { return cTransitionsAbstractTransitionParserRuleCall_2_1_1_1_0; }

		//variables+=VarDef
		public Assignment getVariablesAssignment_2_1_1_2() { return cVariablesAssignment_2_1_1_2; }

		//VarDef
		public RuleCall getVariablesVarDefParserRuleCall_2_1_1_2_0() { return cVariablesVarDefParserRuleCall_2_1_1_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2_1_2() { return cRightCurlyBracketKeyword_2_1_2; }
	}

	public class InitialTransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InitialTransition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInitialTransitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cDoKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cActionAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cActionActionParserRuleCall_2_1_0 = (RuleCall)cActionAssignment_2_1.eContents().get(0);
		
		//InitialTransition: //	('->' target=[State] |	target=[State] '<-')
		//	{InitialTransition} "->" ("do" action=Action)?;
		public ParserRule getRule() { return rule; }

		////	('->' target=[State] |	target=[State] '<-')
		//{InitialTransition} "->" ("do" action=Action)?
		public Group getGroup() { return cGroup; }

		////	('->' target=[State] |	target=[State] '<-')
		//{InitialTransition}
		public Action getInitialTransitionAction_0() { return cInitialTransitionAction_0; }

		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_1() { return cHyphenMinusGreaterThanSignKeyword_1; }

		//("do" action=Action)?
		public Group getGroup_2() { return cGroup_2; }

		//"do"
		public Keyword getDoKeyword_2_0() { return cDoKeyword_2_0; }

		//action=Action
		public Assignment getActionAssignment_2_1() { return cActionAssignment_2_1; }

		//Action
		public RuleCall getActionActionParserRuleCall_2_1_0() { return cActionActionParserRuleCall_2_1_0; }
	}

	public class AbstractStateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AbstractState");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStateMachineParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStateParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AbstractState:
		//	StateMachine | State;
		public ParserRule getRule() { return rule; }

		//StateMachine | State
		public Alternatives getAlternatives() { return cAlternatives; }

		//StateMachine
		public RuleCall getStateMachineParserRuleCall_0() { return cStateMachineParserRuleCall_0; }

		//State
		public RuleCall getStateParserRuleCall_1() { return cStateParserRuleCall_1; }
	}

	public class AbstractTransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AbstractTransition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTransitionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cInternalTransitionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AbstractTransition:
		//	Transition | InternalTransition;
		public ParserRule getRule() { return rule; }

		//Transition | InternalTransition
		public Alternatives getAlternatives() { return cAlternatives; }

		//Transition
		public RuleCall getTransitionParserRuleCall_0() { return cTransitionParserRuleCall_0; }

		//InternalTransition
		public RuleCall getInternalTransitionParserRuleCall_1() { return cInternalTransitionParserRuleCall_1; }
	}

	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Assignment cTargetAssignment_0_0_1 = (Assignment)cGroup_0_0.eContents().get(1);
		private final CrossReference cTargetStateCrossReference_0_0_1_0 = (CrossReference)cTargetAssignment_0_0_1.eContents().get(0);
		private final RuleCall cTargetStateQNAMEParserRuleCall_0_0_1_0_1 = (RuleCall)cTargetStateCrossReference_0_0_1_0.eContents().get(1);
		private final Group cGroup_0_1 = (Group)cAlternatives_0.eContents().get(1);
		private final Assignment cTargetAssignment_0_1_0 = (Assignment)cGroup_0_1.eContents().get(0);
		private final CrossReference cTargetStateCrossReference_0_1_0_0 = (CrossReference)cTargetAssignment_0_1_0.eContents().get(0);
		private final RuleCall cTargetStateQNAMEParserRuleCall_0_1_0_0_1 = (RuleCall)cTargetStateCrossReference_0_1_0_0.eContents().get(1);
		private final Keyword cLessThanSignHyphenMinusKeyword_0_1_1 = (Keyword)cGroup_0_1.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cOnKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cEventAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cEventEventParserRuleCall_1_1_0 = (RuleCall)cEventAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIfKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cConditionAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cConditionConditionParserRuleCall_2_1_0 = (RuleCall)cConditionAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDoKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cActionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cActionActionParserRuleCall_3_1_0 = (RuleCall)cActionAssignment_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Transition:
		//	("->" target=[State|QNAME] // (source=[State|QNAME] '->' target=[State|QNAME] | target=[State|QNAME] '<-' source=[State|QNAME])
		//	| target=[State|QNAME] "<-") ("on" event=Event)? ("if" condition=Condition)? ("do" action=Action)? ";";
		public ParserRule getRule() { return rule; }

		//("->" target=[State|QNAME] // (source=[State|QNAME] '->' target=[State|QNAME] | target=[State|QNAME] '<-' source=[State|QNAME])
		//| target=[State|QNAME] "<-") ("on" event=Event)? ("if" condition=Condition)? ("do" action=Action)? ";"
		public Group getGroup() { return cGroup; }

		//"->" target=[State|QNAME] // (source=[State|QNAME] '->' target=[State|QNAME] | target=[State|QNAME] '<-' source=[State|QNAME])
		//| target=[State|QNAME] "<-"
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//"->" target=[State|QNAME]
		public Group getGroup_0_0() { return cGroup_0_0; }

		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_0_0_0() { return cHyphenMinusGreaterThanSignKeyword_0_0_0; }

		//target=[State|QNAME]
		public Assignment getTargetAssignment_0_0_1() { return cTargetAssignment_0_0_1; }

		//[State|QNAME]
		public CrossReference getTargetStateCrossReference_0_0_1_0() { return cTargetStateCrossReference_0_0_1_0; }

		//QNAME
		public RuleCall getTargetStateQNAMEParserRuleCall_0_0_1_0_1() { return cTargetStateQNAMEParserRuleCall_0_0_1_0_1; }

		//target=[State|QNAME] "<-"
		public Group getGroup_0_1() { return cGroup_0_1; }

		//target=[State|QNAME]
		public Assignment getTargetAssignment_0_1_0() { return cTargetAssignment_0_1_0; }

		//[State|QNAME]
		public CrossReference getTargetStateCrossReference_0_1_0_0() { return cTargetStateCrossReference_0_1_0_0; }

		//QNAME
		public RuleCall getTargetStateQNAMEParserRuleCall_0_1_0_0_1() { return cTargetStateQNAMEParserRuleCall_0_1_0_0_1; }

		//"<-"
		public Keyword getLessThanSignHyphenMinusKeyword_0_1_1() { return cLessThanSignHyphenMinusKeyword_0_1_1; }

		//("on" event=Event)?
		public Group getGroup_1() { return cGroup_1; }

		//"on"
		public Keyword getOnKeyword_1_0() { return cOnKeyword_1_0; }

		//event=Event
		public Assignment getEventAssignment_1_1() { return cEventAssignment_1_1; }

		//Event
		public RuleCall getEventEventParserRuleCall_1_1_0() { return cEventEventParserRuleCall_1_1_0; }

		//("if" condition=Condition)?
		public Group getGroup_2() { return cGroup_2; }

		//"if"
		public Keyword getIfKeyword_2_0() { return cIfKeyword_2_0; }

		//condition=Condition
		public Assignment getConditionAssignment_2_1() { return cConditionAssignment_2_1; }

		//Condition
		public RuleCall getConditionConditionParserRuleCall_2_1_0() { return cConditionConditionParserRuleCall_2_1_0; }

		//("do" action=Action)?
		public Group getGroup_3() { return cGroup_3; }

		//"do"
		public Keyword getDoKeyword_3_0() { return cDoKeyword_3_0; }

		//action=Action
		public Assignment getActionAssignment_3_1() { return cActionAssignment_3_1; }

		//Action
		public RuleCall getActionActionParserRuleCall_3_1_0() { return cActionActionParserRuleCall_3_1_0; }

		//";"
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}

	public class InternalTransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InternalTransition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cOnKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cEventAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cEventEventParserRuleCall_0_1_0 = (RuleCall)cEventAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cIfKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cConditionAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cConditionConditionParserRuleCall_1_1_0 = (RuleCall)cConditionAssignment_1_1.eContents().get(0);
		private final Keyword cDoKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActionActionParserRuleCall_3_0 = (RuleCall)cActionAssignment_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//InternalTransition:
		//	("on" event=Event)? ("if" condition=Condition)? "do" action=Action ";";
		public ParserRule getRule() { return rule; }

		//("on" event=Event)? ("if" condition=Condition)? "do" action=Action ";"
		public Group getGroup() { return cGroup; }

		//("on" event=Event)?
		public Group getGroup_0() { return cGroup_0; }

		//"on"
		public Keyword getOnKeyword_0_0() { return cOnKeyword_0_0; }

		//event=Event
		public Assignment getEventAssignment_0_1() { return cEventAssignment_0_1; }

		//Event
		public RuleCall getEventEventParserRuleCall_0_1_0() { return cEventEventParserRuleCall_0_1_0; }

		//("if" condition=Condition)?
		public Group getGroup_1() { return cGroup_1; }

		//"if"
		public Keyword getIfKeyword_1_0() { return cIfKeyword_1_0; }

		//condition=Condition
		public Assignment getConditionAssignment_1_1() { return cConditionAssignment_1_1; }

		//Condition
		public RuleCall getConditionConditionParserRuleCall_1_1_0() { return cConditionConditionParserRuleCall_1_1_0; }

		//"do"
		public Keyword getDoKeyword_2() { return cDoKeyword_2; }

		//action=Action
		public Assignment getActionAssignment_3() { return cActionAssignment_3; }

		//Action
		public RuleCall getActionActionParserRuleCall_3_0() { return cActionActionParserRuleCall_3_0; }

		//";"
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}

	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Event");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSymbolicEventParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTransitionEventParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cEnterEventParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cExitEventParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cScriptEventParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cTimerEventParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Event:
		//	SymbolicEvent | TransitionEvent | EnterEvent | ExitEvent | ScriptEvent | TimerEvent;
		public ParserRule getRule() { return rule; }

		//SymbolicEvent | TransitionEvent | EnterEvent | ExitEvent | ScriptEvent | TimerEvent
		public Alternatives getAlternatives() { return cAlternatives; }

		//SymbolicEvent
		public RuleCall getSymbolicEventParserRuleCall_0() { return cSymbolicEventParserRuleCall_0; }

		//TransitionEvent
		public RuleCall getTransitionEventParserRuleCall_1() { return cTransitionEventParserRuleCall_1; }

		//EnterEvent
		public RuleCall getEnterEventParserRuleCall_2() { return cEnterEventParserRuleCall_2; }

		//ExitEvent
		public RuleCall getExitEventParserRuleCall_3() { return cExitEventParserRuleCall_3; }

		//ScriptEvent
		public RuleCall getScriptEventParserRuleCall_4() { return cScriptEventParserRuleCall_4; }

		//TimerEvent
		public RuleCall getTimerEventParserRuleCall_5() { return cTimerEventParserRuleCall_5; }
	}

	public class SymbolicEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SymbolicEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cExclamationMarkKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//SymbolicEvent:
		//	name=ID "!";
		public ParserRule getRule() { return rule; }

		//name=ID "!"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"!"
		public Keyword getExclamationMarkKeyword_1() { return cExclamationMarkKeyword_1; }
	}

	public class TransitionEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TransitionEvent");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cAlternatives.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Assignment cSourceAssignment_0_0_0 = (Assignment)cGroup_0_0.eContents().get(0);
		private final CrossReference cSourceStateCrossReference_0_0_0_0 = (CrossReference)cSourceAssignment_0_0_0.eContents().get(0);
		private final RuleCall cSourceStateQNAMEParserRuleCall_0_0_0_0_1 = (RuleCall)cSourceStateCrossReference_0_0_0_0.eContents().get(1);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Assignment cTargetAssignment_0_0_2 = (Assignment)cGroup_0_0.eContents().get(2);
		private final CrossReference cTargetStateCrossReference_0_0_2_0 = (CrossReference)cTargetAssignment_0_0_2.eContents().get(0);
		private final RuleCall cTargetStateQNAMEParserRuleCall_0_0_2_0_1 = (RuleCall)cTargetStateCrossReference_0_0_2_0.eContents().get(1);
		private final Group cGroup_0_1 = (Group)cAlternatives_0.eContents().get(1);
		private final Assignment cTargetAssignment_0_1_0 = (Assignment)cGroup_0_1.eContents().get(0);
		private final CrossReference cTargetStateCrossReference_0_1_0_0 = (CrossReference)cTargetAssignment_0_1_0.eContents().get(0);
		private final RuleCall cTargetStateQNAMEParserRuleCall_0_1_0_0_1 = (RuleCall)cTargetStateCrossReference_0_1_0_0.eContents().get(1);
		private final Keyword cLessThanSignHyphenMinusKeyword_0_1_1 = (Keyword)cGroup_0_1.eContents().get(1);
		private final Assignment cSourceAssignment_0_1_2 = (Assignment)cGroup_0_1.eContents().get(2);
		private final CrossReference cSourceStateCrossReference_0_1_2_0 = (CrossReference)cSourceAssignment_0_1_2.eContents().get(0);
		private final RuleCall cSourceStateQNAMEParserRuleCall_0_1_2_0_1 = (RuleCall)cSourceStateCrossReference_0_1_2_0.eContents().get(1);
		private final Alternatives cAlternatives_1 = (Alternatives)cAlternatives.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Assignment cTargetAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final CrossReference cTargetStateCrossReference_1_0_1_0 = (CrossReference)cTargetAssignment_1_0_1.eContents().get(0);
		private final RuleCall cTargetStateQNAMEParserRuleCall_1_0_1_0_1 = (RuleCall)cTargetStateCrossReference_1_0_1_0.eContents().get(1);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Assignment cTargetAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final CrossReference cTargetStateCrossReference_1_1_0_0 = (CrossReference)cTargetAssignment_1_1_0.eContents().get(0);
		private final RuleCall cTargetStateQNAMEParserRuleCall_1_1_0_0_1 = (RuleCall)cTargetStateCrossReference_1_1_0_0.eContents().get(1);
		private final Keyword cLessThanSignHyphenMinusKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cAlternatives.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Assignment cSourceAssignment_2_0_0 = (Assignment)cGroup_2_0.eContents().get(0);
		private final CrossReference cSourceStateCrossReference_2_0_0_0 = (CrossReference)cSourceAssignment_2_0_0.eContents().get(0);
		private final RuleCall cSourceStateQNAMEParserRuleCall_2_0_0_0_1 = (RuleCall)cSourceStateCrossReference_2_0_0_0.eContents().get(1);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2_0_1 = (Keyword)cGroup_2_0.eContents().get(1);
		private final Group cGroup_2_1 = (Group)cAlternatives_2.eContents().get(1);
		private final Keyword cLessThanSignHyphenMinusKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cSourceAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final CrossReference cSourceStateCrossReference_2_1_1_0 = (CrossReference)cSourceAssignment_2_1_1.eContents().get(0);
		private final RuleCall cSourceStateQNAMEParserRuleCall_2_1_1_0_1 = (RuleCall)cSourceStateCrossReference_2_1_1_0.eContents().get(1);
		
		//TransitionEvent:
		//	(source=[State|QNAME] "->" target=[State|QNAME] | target=[State|QNAME] "<-" source=[State|QNAME]) | ("->"
		//	target=[State|QNAME] // implicit EnterEvent
		//	| target=[State|QNAME] "<-") | (source=[State|QNAME] "->" // implicit ExitEvent
		//	| "<-" source=[State|QNAME]);
		public ParserRule getRule() { return rule; }

		//(source=[State|QNAME] "->" target=[State|QNAME] | target=[State|QNAME] "<-" source=[State|QNAME]) | ("->"
		//target=[State|QNAME] // implicit EnterEvent
		//| target=[State|QNAME] "<-") | (source=[State|QNAME] "->" // implicit ExitEvent
		//| "<-" source=[State|QNAME])
		public Alternatives getAlternatives() { return cAlternatives; }

		//source=[State|QNAME] "->" target=[State|QNAME] | target=[State|QNAME] "<-" source=[State|QNAME]
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//source=[State|QNAME] "->" target=[State|QNAME]
		public Group getGroup_0_0() { return cGroup_0_0; }

		//source=[State|QNAME]
		public Assignment getSourceAssignment_0_0_0() { return cSourceAssignment_0_0_0; }

		//[State|QNAME]
		public CrossReference getSourceStateCrossReference_0_0_0_0() { return cSourceStateCrossReference_0_0_0_0; }

		//QNAME
		public RuleCall getSourceStateQNAMEParserRuleCall_0_0_0_0_1() { return cSourceStateQNAMEParserRuleCall_0_0_0_0_1; }

		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_0_0_1() { return cHyphenMinusGreaterThanSignKeyword_0_0_1; }

		//target=[State|QNAME]
		public Assignment getTargetAssignment_0_0_2() { return cTargetAssignment_0_0_2; }

		//[State|QNAME]
		public CrossReference getTargetStateCrossReference_0_0_2_0() { return cTargetStateCrossReference_0_0_2_0; }

		//QNAME
		public RuleCall getTargetStateQNAMEParserRuleCall_0_0_2_0_1() { return cTargetStateQNAMEParserRuleCall_0_0_2_0_1; }

		//target=[State|QNAME] "<-" source=[State|QNAME]
		public Group getGroup_0_1() { return cGroup_0_1; }

		//target=[State|QNAME]
		public Assignment getTargetAssignment_0_1_0() { return cTargetAssignment_0_1_0; }

		//[State|QNAME]
		public CrossReference getTargetStateCrossReference_0_1_0_0() { return cTargetStateCrossReference_0_1_0_0; }

		//QNAME
		public RuleCall getTargetStateQNAMEParserRuleCall_0_1_0_0_1() { return cTargetStateQNAMEParserRuleCall_0_1_0_0_1; }

		//"<-"
		public Keyword getLessThanSignHyphenMinusKeyword_0_1_1() { return cLessThanSignHyphenMinusKeyword_0_1_1; }

		//source=[State|QNAME]
		public Assignment getSourceAssignment_0_1_2() { return cSourceAssignment_0_1_2; }

		//[State|QNAME]
		public CrossReference getSourceStateCrossReference_0_1_2_0() { return cSourceStateCrossReference_0_1_2_0; }

		//QNAME
		public RuleCall getSourceStateQNAMEParserRuleCall_0_1_2_0_1() { return cSourceStateQNAMEParserRuleCall_0_1_2_0_1; }

		//"->" target=[State|QNAME] // implicit EnterEvent
		//| target=[State|QNAME] "<-"
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//"->" target=[State|QNAME]
		public Group getGroup_1_0() { return cGroup_1_0; }

		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_1_0_0() { return cHyphenMinusGreaterThanSignKeyword_1_0_0; }

		//target=[State|QNAME]
		public Assignment getTargetAssignment_1_0_1() { return cTargetAssignment_1_0_1; }

		//[State|QNAME]
		public CrossReference getTargetStateCrossReference_1_0_1_0() { return cTargetStateCrossReference_1_0_1_0; }

		//QNAME
		public RuleCall getTargetStateQNAMEParserRuleCall_1_0_1_0_1() { return cTargetStateQNAMEParserRuleCall_1_0_1_0_1; }

		//target=[State|QNAME] "<-"
		public Group getGroup_1_1() { return cGroup_1_1; }

		//target=[State|QNAME]
		public Assignment getTargetAssignment_1_1_0() { return cTargetAssignment_1_1_0; }

		//[State|QNAME]
		public CrossReference getTargetStateCrossReference_1_1_0_0() { return cTargetStateCrossReference_1_1_0_0; }

		//QNAME
		public RuleCall getTargetStateQNAMEParserRuleCall_1_1_0_0_1() { return cTargetStateQNAMEParserRuleCall_1_1_0_0_1; }

		//"<-"
		public Keyword getLessThanSignHyphenMinusKeyword_1_1_1() { return cLessThanSignHyphenMinusKeyword_1_1_1; }

		//source=[State|QNAME] "->" // implicit ExitEvent
		//| "<-" source=[State|QNAME]
		public Alternatives getAlternatives_2() { return cAlternatives_2; }

		//source=[State|QNAME] "->"
		public Group getGroup_2_0() { return cGroup_2_0; }

		//source=[State|QNAME]
		public Assignment getSourceAssignment_2_0_0() { return cSourceAssignment_2_0_0; }

		//[State|QNAME]
		public CrossReference getSourceStateCrossReference_2_0_0_0() { return cSourceStateCrossReference_2_0_0_0; }

		//QNAME
		public RuleCall getSourceStateQNAMEParserRuleCall_2_0_0_0_1() { return cSourceStateQNAMEParserRuleCall_2_0_0_0_1; }

		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_2_0_1() { return cHyphenMinusGreaterThanSignKeyword_2_0_1; }

		//"<-" source=[State|QNAME]
		public Group getGroup_2_1() { return cGroup_2_1; }

		//"<-"
		public Keyword getLessThanSignHyphenMinusKeyword_2_1_0() { return cLessThanSignHyphenMinusKeyword_2_1_0; }

		//source=[State|QNAME]
		public Assignment getSourceAssignment_2_1_1() { return cSourceAssignment_2_1_1; }

		//[State|QNAME]
		public CrossReference getSourceStateCrossReference_2_1_1_0() { return cSourceStateCrossReference_2_1_1_0; }

		//QNAME
		public RuleCall getSourceStateQNAMEParserRuleCall_2_1_1_0_1() { return cSourceStateQNAMEParserRuleCall_2_1_1_0_1; }
	}

	public class EnterEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EnterEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEnterEventAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEnterKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//EnterEvent:
		//	{EnterEvent} "enter";
		public ParserRule getRule() { return rule; }

		//{EnterEvent} "enter"
		public Group getGroup() { return cGroup; }

		//{EnterEvent}
		public Action getEnterEventAction_0() { return cEnterEventAction_0; }

		//"enter"
		public Keyword getEnterKeyword_1() { return cEnterKeyword_1; }
	}

	public class ExitEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExitEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cExitEventAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cExitKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//ExitEvent:
		//	{ExitEvent} "exit";
		public ParserRule getRule() { return rule; }

		//{ExitEvent} "exit"
		public Group getGroup() { return cGroup; }

		//{ExitEvent}
		public Action getExitEventAction_0() { return cExitEventAction_0; }

		//"exit"
		public Keyword getExitKeyword_1() { return cExitKeyword_1; }
	}

	public class ScriptEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ScriptEvent");
		private final Assignment cScriptAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cScriptSCRIPT_EXPRESSIONTerminalRuleCall_0 = (RuleCall)cScriptAssignment.eContents().get(0);
		
		//ScriptEvent:
		//	script=SCRIPT_EXPRESSION;
		public ParserRule getRule() { return rule; }

		//script=SCRIPT_EXPRESSION
		public Assignment getScriptAssignment() { return cScriptAssignment; }

		//SCRIPT_EXPRESSION
		public RuleCall getScriptSCRIPT_EXPRESSIONTerminalRuleCall_0() { return cScriptSCRIPT_EXPRESSIONTerminalRuleCall_0; }
	}

	public class TimerEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TimerEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDelayAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDelayExpressionParserRuleCall_2_0 = (RuleCall)cDelayAssignment_2.eContents().get(0);
		private final Keyword cAfterKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cEventAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEventEventParserRuleCall_4_0 = (RuleCall)cEventAssignment_4.eContents().get(0);
		
		//TimerEvent:
		//	"t" ">" delay=Expression "after" event=Event;
		public ParserRule getRule() { return rule; }

		//"t" ">" delay=Expression "after" event=Event
		public Group getGroup() { return cGroup; }

		//"t"
		public Keyword getTKeyword_0() { return cTKeyword_0; }

		//">"
		public Keyword getGreaterThanSignKeyword_1() { return cGreaterThanSignKeyword_1; }

		//delay=Expression
		public Assignment getDelayAssignment_2() { return cDelayAssignment_2; }

		//Expression
		public RuleCall getDelayExpressionParserRuleCall_2_0() { return cDelayExpressionParserRuleCall_2_0; }

		//"after"
		public Keyword getAfterKeyword_3() { return cAfterKeyword_3; }

		//event=Event
		public Assignment getEventAssignment_4() { return cEventAssignment_4; }

		//Event
		public RuleCall getEventEventParserRuleCall_4_0() { return cEventEventParserRuleCall_4_0; }
	}

	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Condition");
		private final Assignment cScriptAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cScriptSCRIPT_EXPRESSIONTerminalRuleCall_0 = (RuleCall)cScriptAssignment.eContents().get(0);
		
		//Condition:
		//	script=SCRIPT_EXPRESSION;
		public ParserRule getRule() { return rule; }

		//script=SCRIPT_EXPRESSION
		public Assignment getScriptAssignment() { return cScriptAssignment; }

		//SCRIPT_EXPRESSION
		public RuleCall getScriptSCRIPT_EXPRESSIONTerminalRuleCall_0() { return cScriptSCRIPT_EXPRESSIONTerminalRuleCall_0; }
	}

	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Action");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSymbolicActionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cScriptActionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAssignmentActionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Action:
		//	SymbolicAction | ScriptAction | AssignmentAction;
		public ParserRule getRule() { return rule; }

		//SymbolicAction | ScriptAction | AssignmentAction
		public Alternatives getAlternatives() { return cAlternatives; }

		//SymbolicAction
		public RuleCall getSymbolicActionParserRuleCall_0() { return cSymbolicActionParserRuleCall_0; }

		//ScriptAction
		public RuleCall getScriptActionParserRuleCall_1() { return cScriptActionParserRuleCall_1; }

		//AssignmentAction
		public RuleCall getAssignmentActionParserRuleCall_2() { return cAssignmentActionParserRuleCall_2; }
	}

	public class SymbolicActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SymbolicAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cAfterKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cDelayAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cDelayExpressionParserRuleCall_1_1_0 = (RuleCall)cDelayAssignment_1_1.eContents().get(0);
		private final Keyword cExclamationMarkKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//SymbolicAction:
		//	name=ID ("after" delay=Expression)? "!";
		public ParserRule getRule() { return rule; }

		//name=ID ("after" delay=Expression)? "!"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//("after" delay=Expression)?
		public Group getGroup_1() { return cGroup_1; }

		//"after"
		public Keyword getAfterKeyword_1_0() { return cAfterKeyword_1_0; }

		//delay=Expression
		public Assignment getDelayAssignment_1_1() { return cDelayAssignment_1_1; }

		//Expression
		public RuleCall getDelayExpressionParserRuleCall_1_1_0() { return cDelayExpressionParserRuleCall_1_1_0; }

		//"!"
		public Keyword getExclamationMarkKeyword_2() { return cExclamationMarkKeyword_2; }
	}

	public class ScriptActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ScriptAction");
		private final Assignment cScriptAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cScriptSCRIPT_STATEMENTSTerminalRuleCall_0 = (RuleCall)cScriptAssignment.eContents().get(0);
		
		//ScriptAction:
		//	script=SCRIPT_STATEMENTS;
		public ParserRule getRule() { return rule; }

		//script=SCRIPT_STATEMENTS
		public Assignment getScriptAssignment() { return cScriptAssignment; }

		//SCRIPT_STATEMENTS
		public RuleCall getScriptSCRIPT_STATEMENTSTerminalRuleCall_0() { return cScriptSCRIPT_STATEMENTSTerminalRuleCall_0; }
	}

	public class VarDefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VarDef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cETypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cETypeEClassifierCrossReference_2_1_0 = (CrossReference)cETypeAssignment_2_1.eContents().get(0);
		private final RuleCall cETypeEClassifierQNAMEParserRuleCall_2_1_0_1 = (RuleCall)cETypeEClassifierCrossReference_2_1_0.eContents().get(1);
		private final Assignment cManyAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final Alternatives cManyAlternatives_2_2_0 = (Alternatives)cManyAssignment_2_2.eContents().get(0);
		private final Keyword cManyAsteriskKeyword_2_2_0_0 = (Keyword)cManyAlternatives_2_2_0.eContents().get(0);
		private final Keyword cManyLeftSquareBracketRightSquareBracketKeyword_2_2_0_1 = (Keyword)cManyAlternatives_2_2_0.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cInitAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cInitExpressionParserRuleCall_3_1_0 = (RuleCall)cInitAssignment_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//VarDef:
		//	"var" name=ID (":" eType=[ecore::EClassifier|QNAME] many?=("*" | "[]")?)? ("=" init=Expression)? ";";
		public ParserRule getRule() { return rule; }

		//"var" name=ID (":" eType=[ecore::EClassifier|QNAME] many?=("*" | "[]")?)? ("=" init=Expression)? ";"
		public Group getGroup() { return cGroup; }

		//"var"
		public Keyword getVarKeyword_0() { return cVarKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//(":" eType=[ecore::EClassifier|QNAME] many?=("*" | "[]")?)?
		public Group getGroup_2() { return cGroup_2; }

		//":"
		public Keyword getColonKeyword_2_0() { return cColonKeyword_2_0; }

		//eType=[ecore::EClassifier|QNAME]
		public Assignment getETypeAssignment_2_1() { return cETypeAssignment_2_1; }

		//[ecore::EClassifier|QNAME]
		public CrossReference getETypeEClassifierCrossReference_2_1_0() { return cETypeEClassifierCrossReference_2_1_0; }

		//QNAME
		public RuleCall getETypeEClassifierQNAMEParserRuleCall_2_1_0_1() { return cETypeEClassifierQNAMEParserRuleCall_2_1_0_1; }

		//many?=("*" | "[]")?
		public Assignment getManyAssignment_2_2() { return cManyAssignment_2_2; }

		//"*" | "[]"
		public Alternatives getManyAlternatives_2_2_0() { return cManyAlternatives_2_2_0; }

		//"*"
		public Keyword getManyAsteriskKeyword_2_2_0_0() { return cManyAsteriskKeyword_2_2_0_0; }

		//"[]"
		public Keyword getManyLeftSquareBracketRightSquareBracketKeyword_2_2_0_1() { return cManyLeftSquareBracketRightSquareBracketKeyword_2_2_0_1; }

		//("=" init=Expression)?
		public Group getGroup_3() { return cGroup_3; }

		//"="
		public Keyword getEqualsSignKeyword_3_0() { return cEqualsSignKeyword_3_0; }

		//init=Expression
		public Assignment getInitAssignment_3_1() { return cInitAssignment_3_1; }

		//Expression
		public RuleCall getInitExpressionParserRuleCall_3_1_0() { return cInitExpressionParserRuleCall_3_1_0; }

		//";"
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}

	public class AssignmentActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AssignmentAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVarAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cVarVarDefCrossReference_0_0 = (CrossReference)cVarAssignment_0.eContents().get(0);
		private final RuleCall cVarVarDefQNAMEParserRuleCall_0_0_1 = (RuleCall)cVarVarDefCrossReference_0_0.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueExpressionParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//AssignmentAction:
		//	var=[VarDef|QNAME] "=" value=Expression;
		public ParserRule getRule() { return rule; }

		//var=[VarDef|QNAME] "=" value=Expression
		public Group getGroup() { return cGroup; }

		//var=[VarDef|QNAME]
		public Assignment getVarAssignment_0() { return cVarAssignment_0; }

		//[VarDef|QNAME]
		public CrossReference getVarVarDefCrossReference_0_0() { return cVarVarDefCrossReference_0_0; }

		//QNAME
		public RuleCall getVarVarDefQNAMEParserRuleCall_0_0_1() { return cVarVarDefQNAMEParserRuleCall_0_0_1; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=Expression
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//Expression
		public RuleCall getValueExpressionParserRuleCall_2_0() { return cValueExpressionParserRuleCall_2_0; }
	}

	public class BOOLEAN_LITERALElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BOOLEAN_LITERAL");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//BOOLEAN_LITERAL returns ecore::EBoolean:
		//	"true" | "false";
		public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class FLOAT_LITERALElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FLOAT_LITERAL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_0_0 = (RuleCall)cAlternatives_0.eContents().get(0);
		private final RuleCall cPOS_INTParserRuleCall_0_1 = (RuleCall)cAlternatives_0.eContents().get(1);
		private final RuleCall cNEG_INTParserRuleCall_0_2 = (RuleCall)cAlternatives_0.eContents().get(2);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//FLOAT_LITERAL returns ecore::EDouble:
		//	(INT | POS_INT | NEG_INT) "." INT;
		public ParserRule getRule() { return rule; }

		//(INT | POS_INT | NEG_INT) "." INT
		public Group getGroup() { return cGroup; }

		//INT | POS_INT | NEG_INT
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_0_0() { return cINTTerminalRuleCall_0_0; }

		//POS_INT
		public RuleCall getPOS_INTParserRuleCall_0_1() { return cPOS_INTParserRuleCall_0_1; }

		//NEG_INT
		public RuleCall getNEG_INTParserRuleCall_0_2() { return cNEG_INTParserRuleCall_0_2; }

		//"."
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}

	public class POS_INTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "POS_INT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlusSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//POS_INT returns ecore::EInt:
		//	"+" INT;
		public ParserRule getRule() { return rule; }

		//"+" INT
		public Group getGroup() { return cGroup; }

		//"+"
		public Keyword getPlusSignKeyword_0() { return cPlusSignKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class NEG_INTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NEG_INT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//NEG_INT returns ecore::EInt:
		//	"-" INT;
		public ParserRule getRule() { return rule; }

		//"-" INT
		public Group getGroup() { return cGroup; }

		//"-"
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class QNAMEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QNAME");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QNAME returns ecore::EString:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}

	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLiteralParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cScriptExpressionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cEPathParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Expression:
		//	Literal | ScriptExpression | EPath;
		public ParserRule getRule() { return rule; }

		//Literal | ScriptExpression | EPath
		public Alternatives getAlternatives() { return cAlternatives; }

		//Literal
		public RuleCall getLiteralParserRuleCall_0() { return cLiteralParserRuleCall_0; }

		//ScriptExpression
		public RuleCall getScriptExpressionParserRuleCall_1() { return cScriptExpressionParserRuleCall_1; }

		//EPath
		public RuleCall getEPathParserRuleCall_2() { return cEPathParserRuleCall_2; }
	}

	public class LiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Literal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBooleanLiteralParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFloatLiteralParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cIntLiteralParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cStringLiteralParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cUriLiteralParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cEObjectUriLiteralParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cDelayLiteralParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Literal:
		//	BooleanLiteral | FloatLiteral | IntLiteral | StringLiteral | UriLiteral | EObjectUriLiteral | DelayLiteral;
		public ParserRule getRule() { return rule; }

		//BooleanLiteral | FloatLiteral | IntLiteral | StringLiteral | UriLiteral | EObjectUriLiteral | DelayLiteral
		public Alternatives getAlternatives() { return cAlternatives; }

		//BooleanLiteral
		public RuleCall getBooleanLiteralParserRuleCall_0() { return cBooleanLiteralParserRuleCall_0; }

		//FloatLiteral
		public RuleCall getFloatLiteralParserRuleCall_1() { return cFloatLiteralParserRuleCall_1; }

		//IntLiteral
		public RuleCall getIntLiteralParserRuleCall_2() { return cIntLiteralParserRuleCall_2; }

		//StringLiteral
		public RuleCall getStringLiteralParserRuleCall_3() { return cStringLiteralParserRuleCall_3; }

		//UriLiteral
		public RuleCall getUriLiteralParserRuleCall_4() { return cUriLiteralParserRuleCall_4; }

		//EObjectUriLiteral
		public RuleCall getEObjectUriLiteralParserRuleCall_5() { return cEObjectUriLiteralParserRuleCall_5; }

		//DelayLiteral
		public RuleCall getDelayLiteralParserRuleCall_6() { return cDelayLiteralParserRuleCall_6; }
	}

	public class BooleanLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BooleanLiteral");
		private final Assignment cBooleanValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cBooleanValueBOOLEAN_LITERALParserRuleCall_0 = (RuleCall)cBooleanValueAssignment.eContents().get(0);
		
		//BooleanLiteral:
		//	booleanValue=BOOLEAN_LITERAL;
		public ParserRule getRule() { return rule; }

		//booleanValue=BOOLEAN_LITERAL
		public Assignment getBooleanValueAssignment() { return cBooleanValueAssignment; }

		//BOOLEAN_LITERAL
		public RuleCall getBooleanValueBOOLEAN_LITERALParserRuleCall_0() { return cBooleanValueBOOLEAN_LITERALParserRuleCall_0; }
	}

	public class IntLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IntLiteral");
		private final Assignment cIntValueAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cIntValueAlternatives_0 = (Alternatives)cIntValueAssignment.eContents().get(0);
		private final RuleCall cIntValueINTTerminalRuleCall_0_0 = (RuleCall)cIntValueAlternatives_0.eContents().get(0);
		private final RuleCall cIntValuePOS_INTParserRuleCall_0_1 = (RuleCall)cIntValueAlternatives_0.eContents().get(1);
		private final RuleCall cIntValueNEG_INTParserRuleCall_0_2 = (RuleCall)cIntValueAlternatives_0.eContents().get(2);
		
		//IntLiteral:
		//	intValue=(INT | POS_INT | NEG_INT);
		public ParserRule getRule() { return rule; }

		//intValue=(INT | POS_INT | NEG_INT)
		public Assignment getIntValueAssignment() { return cIntValueAssignment; }

		//INT | POS_INT | NEG_INT
		public Alternatives getIntValueAlternatives_0() { return cIntValueAlternatives_0; }

		//INT
		public RuleCall getIntValueINTTerminalRuleCall_0_0() { return cIntValueINTTerminalRuleCall_0_0; }

		//POS_INT
		public RuleCall getIntValuePOS_INTParserRuleCall_0_1() { return cIntValuePOS_INTParserRuleCall_0_1; }

		//NEG_INT
		public RuleCall getIntValueNEG_INTParserRuleCall_0_2() { return cIntValueNEG_INTParserRuleCall_0_2; }
	}

	public class FloatLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FloatLiteral");
		private final Assignment cFloatValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cFloatValueFLOAT_LITERALParserRuleCall_0 = (RuleCall)cFloatValueAssignment.eContents().get(0);
		
		//FloatLiteral:
		//	floatValue=FLOAT_LITERAL;
		public ParserRule getRule() { return rule; }

		//floatValue=FLOAT_LITERAL
		public Assignment getFloatValueAssignment() { return cFloatValueAssignment; }

		//FLOAT_LITERAL
		public RuleCall getFloatValueFLOAT_LITERALParserRuleCall_0() { return cFloatValueFLOAT_LITERALParserRuleCall_0; }
	}

	public class StringLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StringLiteral");
		private final Assignment cStringValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cStringValueSTRINGTerminalRuleCall_0 = (RuleCall)cStringValueAssignment.eContents().get(0);
		
		//StringLiteral:
		//	stringValue=STRING;
		public ParserRule getRule() { return rule; }

		//stringValue=STRING
		public Assignment getStringValueAssignment() { return cStringValueAssignment; }

		//STRING
		public RuleCall getStringValueSTRINGTerminalRuleCall_0() { return cStringValueSTRINGTerminalRuleCall_0; }
	}

	public class UriLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UriLiteral");
		private final Assignment cUriAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cUriURI_LITERALTerminalRuleCall_0 = (RuleCall)cUriAssignment.eContents().get(0);
		
		//UriLiteral:
		//	uri=URI_LITERAL;
		public ParserRule getRule() { return rule; }

		//uri=URI_LITERAL
		public Assignment getUriAssignment() { return cUriAssignment; }

		//URI_LITERAL
		public RuleCall getUriURI_LITERALTerminalRuleCall_0() { return cUriURI_LITERALTerminalRuleCall_0; }
	}

	public class EObjectUriLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EObjectUriLiteral");
		private final Assignment cUriAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cUriEOBJECT_URI_LITERALTerminalRuleCall_0 = (RuleCall)cUriAssignment.eContents().get(0);
		
		//EObjectUriLiteral:
		//	uri=EOBJECT_URI_LITERAL;
		public ParserRule getRule() { return rule; }

		//uri=EOBJECT_URI_LITERAL
		public Assignment getUriAssignment() { return cUriAssignment; }

		//EOBJECT_URI_LITERAL
		public RuleCall getUriEOBJECT_URI_LITERALTerminalRuleCall_0() { return cUriEOBJECT_URI_LITERALTerminalRuleCall_0; }
	}

	public class DelayLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DelayLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIntValueAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cIntValueINTTerminalRuleCall_0_0 = (RuleCall)cIntValueAssignment_0.eContents().get(0);
		private final Assignment cTimeUnitAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTimeUnitTimeUnitEnumRuleCall_1_0 = (RuleCall)cTimeUnitAssignment_1.eContents().get(0);
		
		//DelayLiteral:
		//	intValue=INT timeUnit=TimeUnit;
		public ParserRule getRule() { return rule; }

		//intValue=INT timeUnit=TimeUnit
		public Group getGroup() { return cGroup; }

		//intValue=INT
		public Assignment getIntValueAssignment_0() { return cIntValueAssignment_0; }

		//INT
		public RuleCall getIntValueINTTerminalRuleCall_0_0() { return cIntValueINTTerminalRuleCall_0_0; }

		//timeUnit=TimeUnit
		public Assignment getTimeUnitAssignment_1() { return cTimeUnitAssignment_1; }

		//TimeUnit
		public RuleCall getTimeUnitTimeUnitEnumRuleCall_1_0() { return cTimeUnitTimeUnitEnumRuleCall_1_0; }
	}

	public class VarRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VarRef");
		private final Assignment cVarAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cVarVarDefCrossReference_0 = (CrossReference)cVarAssignment.eContents().get(0);
		private final RuleCall cVarVarDefQNAMEParserRuleCall_0_1 = (RuleCall)cVarVarDefCrossReference_0.eContents().get(1);
		
		//VarRef:
		//	var=[VarDef|QNAME];
		public ParserRule getRule() { return rule; }

		//var=[VarDef|QNAME]
		public Assignment getVarAssignment() { return cVarAssignment; }

		//[VarDef|QNAME]
		public CrossReference getVarVarDefCrossReference_0() { return cVarVarDefCrossReference_0; }

		//QNAME
		public RuleCall getVarVarDefQNAMEParserRuleCall_0_1() { return cVarVarDefQNAMEParserRuleCall_0_1; }
	}

	public class EPathElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EPath");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVarAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cVarVarRefParserRuleCall_0_0 = (RuleCall)cVarAssignment_0.eContents().get(0);
		private final Assignment cStepsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStepsEStepParserRuleCall_1_0 = (RuleCall)cStepsAssignment_1.eContents().get(0);
		
		//EPath:
		//	var=VarRef steps+=EStep*;
		public ParserRule getRule() { return rule; }

		//var=VarRef steps+=EStep*
		public Group getGroup() { return cGroup; }

		//var=VarRef
		public Assignment getVarAssignment_0() { return cVarAssignment_0; }

		//VarRef
		public RuleCall getVarVarRefParserRuleCall_0_0() { return cVarVarRefParserRuleCall_0_0; }

		//steps+=EStep*
		public Assignment getStepsAssignment_1() { return cStepsAssignment_1; }

		//EStep
		public RuleCall getStepsEStepParserRuleCall_1_0() { return cStepsEStepParserRuleCall_1_0; }
	}

	public class EStepElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EStep");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSolidusSpaceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cFeatureNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cFeatureNameIDTerminalRuleCall_1_0 = (RuleCall)cFeatureNameAssignment_1.eContents().get(0);
		private final Assignment cFilterAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFilterEStepFilterParserRuleCall_2_0 = (RuleCall)cFilterAssignment_2.eContents().get(0);
		
		//EStep:
		//	"/ " featureName=ID filter=EStepFilter?;
		public ParserRule getRule() { return rule; }

		//"/ " featureName=ID filter=EStepFilter?
		public Group getGroup() { return cGroup; }

		//"/ "
		public Keyword getSolidusSpaceKeyword_0() { return cSolidusSpaceKeyword_0; }

		//featureName=ID
		public Assignment getFeatureNameAssignment_1() { return cFeatureNameAssignment_1; }

		//ID
		public RuleCall getFeatureNameIDTerminalRuleCall_1_0() { return cFeatureNameIDTerminalRuleCall_1_0; }

		//filter=EStepFilter?
		public Assignment getFilterAssignment_2() { return cFilterAssignment_2; }

		//EStepFilter
		public RuleCall getFilterEStepFilterParserRuleCall_2_0() { return cFilterEStepFilterParserRuleCall_2_0; }
	}

	public class EStepFilterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EStepFilter");
		private final Assignment cScriptAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cScriptScriptExpressionParserRuleCall_0 = (RuleCall)cScriptAssignment.eContents().get(0);
		
		//EStepFilter:
		//	script=ScriptExpression;
		public ParserRule getRule() { return rule; }

		//script=ScriptExpression
		public Assignment getScriptAssignment() { return cScriptAssignment; }

		//ScriptExpression
		public RuleCall getScriptScriptExpressionParserRuleCall_0() { return cScriptScriptExpressionParserRuleCall_0; }
	}

	public class ScriptExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ScriptExpression");
		private final Assignment cScriptAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cScriptSCRIPT_EXPRESSIONTerminalRuleCall_0 = (RuleCall)cScriptAssignment.eContents().get(0);
		
		//ScriptExpression:
		//	script=SCRIPT_EXPRESSION;
		public ParserRule getRule() { return rule; }

		//script=SCRIPT_EXPRESSION
		public Assignment getScriptAssignment() { return cScriptAssignment; }

		//SCRIPT_EXPRESSION
		public RuleCall getScriptSCRIPT_EXPRESSIONTerminalRuleCall_0() { return cScriptSCRIPT_EXPRESSIONTerminalRuleCall_0; }
	}
	
	
	public class TimeUnitElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "TimeUnit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMsEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMsMsKeyword_0_0 = (Keyword)cMsEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSSKeyword_1_0 = (Keyword)cSEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMMKeyword_2_0 = (Keyword)cMEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cHEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cHHKeyword_3_0 = (Keyword)cHEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum TimeUnit:
		//	ms | s | m | h;
		public EnumRule getRule() { return rule; }

		//ms | s | m | h
		public Alternatives getAlternatives() { return cAlternatives; }

		//ms
		public EnumLiteralDeclaration getMsEnumLiteralDeclaration_0() { return cMsEnumLiteralDeclaration_0; }

		//"ms"
		public Keyword getMsMsKeyword_0_0() { return cMsMsKeyword_0_0; }

		//s
		public EnumLiteralDeclaration getSEnumLiteralDeclaration_1() { return cSEnumLiteralDeclaration_1; }

		//"s"
		public Keyword getSSKeyword_1_0() { return cSSKeyword_1_0; }

		//m
		public EnumLiteralDeclaration getMEnumLiteralDeclaration_2() { return cMEnumLiteralDeclaration_2; }

		//"m"
		public Keyword getMMKeyword_2_0() { return cMMKeyword_2_0; }

		//h
		public EnumLiteralDeclaration getHEnumLiteralDeclaration_3() { return cHEnumLiteralDeclaration_3; }

		//"h"
		public Keyword getHHKeyword_3_0() { return cHHKeyword_3_0; }
	}
	
	private StateMachineElements pStateMachine;
	private ResourceImportElements pResourceImport;
	private DomainModelImportElements pDomainModelImport;
	private DomainDataImportElements pDomainDataImport;
	private StateElements pState;
	private InitialTransitionElements pInitialTransition;
	private AbstractStateElements pAbstractState;
	private AbstractTransitionElements pAbstractTransition;
	private TransitionElements pTransition;
	private InternalTransitionElements pInternalTransition;
	private EventElements pEvent;
	private SymbolicEventElements pSymbolicEvent;
	private TransitionEventElements pTransitionEvent;
	private EnterEventElements pEnterEvent;
	private ExitEventElements pExitEvent;
	private ScriptEventElements pScriptEvent;
	private TimerEventElements pTimerEvent;
	private ConditionElements pCondition;
	private ActionElements pAction;
	private SymbolicActionElements pSymbolicAction;
	private ScriptActionElements pScriptAction;
	private VarDefElements pVarDef;
	private AssignmentActionElements pAssignmentAction;
	private TerminalRule tSCRIPT_EXPRESSION;
	private TerminalRule tSCRIPT_STATEMENTS;
	private TerminalRule tURI_LITERAL;
	private TerminalRule tEOBJECT_URI_LITERAL;
	private BOOLEAN_LITERALElements pBOOLEAN_LITERAL;
	private FLOAT_LITERALElements pFLOAT_LITERAL;
	private POS_INTElements pPOS_INT;
	private NEG_INTElements pNEG_INT;
	private QNAMEElements pQNAME;
	private ExpressionElements pExpression;
	private LiteralElements pLiteral;
	private BooleanLiteralElements pBooleanLiteral;
	private IntLiteralElements pIntLiteral;
	private FloatLiteralElements pFloatLiteral;
	private StringLiteralElements pStringLiteral;
	private UriLiteralElements pUriLiteral;
	private EObjectUriLiteralElements pEObjectUriLiteral;
	private TimeUnitElements unknownRuleTimeUnit;
	private DelayLiteralElements pDelayLiteral;
	private VarRefElements pVarRef;
	private EPathElements pEPath;
	private EStepElements pEStep;
	private EStepFilterElements pEStepFilter;
	private ScriptExpressionElements pScriptExpression;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public ScxmlxtGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//StateMachine:
	//	imports+=ResourceImport* (states+=State | transitions+=AbstractTransition | variables+=VarDef)*;
	public StateMachineElements getStateMachineAccess() {
		return (pStateMachine != null) ? pStateMachine : (pStateMachine = new StateMachineElements());
	}
	
	public ParserRule getStateMachineRule() {
		return getStateMachineAccess().getRule();
	}

	//ResourceImport:
	//	DomainModelImport | DomainDataImport;
	public ResourceImportElements getResourceImportAccess() {
		return (pResourceImport != null) ? pResourceImport : (pResourceImport = new ResourceImportElements());
	}
	
	public ParserRule getResourceImportRule() {
		return getResourceImportAccess().getRule();
	}

	//DomainModelImport:
	//	"domain"? "model" importURI=STRING ";";
	public DomainModelImportElements getDomainModelImportAccess() {
		return (pDomainModelImport != null) ? pDomainModelImport : (pDomainModelImport = new DomainModelImportElements());
	}
	
	public ParserRule getDomainModelImportRule() {
		return getDomainModelImportAccess().getRule();
	}

	//DomainDataImport:
	//	"domain"? "data" importURI=STRING ";";
	public DomainDataImportElements getDomainDataImportAccess() {
		return (pDomainDataImport != null) ? pDomainDataImport : (pDomainDataImport = new DomainDataImportElements());
	}
	
	public ParserRule getDomainDataImportRule() {
		return getDomainDataImportAccess().getRule();
	}

	//State:
	//	initialTransition=InitialTransition? name=ID (";" | "{" (states+=State | transitions+=AbstractTransition |
	//	variables+=VarDef)* "}");
	public StateElements getStateAccess() {
		return (pState != null) ? pState : (pState = new StateElements());
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}

	//InitialTransition: //	('->' target=[State] |	target=[State] '<-')
	//	{InitialTransition} "->" ("do" action=Action)?;
	public InitialTransitionElements getInitialTransitionAccess() {
		return (pInitialTransition != null) ? pInitialTransition : (pInitialTransition = new InitialTransitionElements());
	}
	
	public ParserRule getInitialTransitionRule() {
		return getInitialTransitionAccess().getRule();
	}

	//AbstractState:
	//	StateMachine | State;
	public AbstractStateElements getAbstractStateAccess() {
		return (pAbstractState != null) ? pAbstractState : (pAbstractState = new AbstractStateElements());
	}
	
	public ParserRule getAbstractStateRule() {
		return getAbstractStateAccess().getRule();
	}

	//AbstractTransition:
	//	Transition | InternalTransition;
	public AbstractTransitionElements getAbstractTransitionAccess() {
		return (pAbstractTransition != null) ? pAbstractTransition : (pAbstractTransition = new AbstractTransitionElements());
	}
	
	public ParserRule getAbstractTransitionRule() {
		return getAbstractTransitionAccess().getRule();
	}

	//Transition:
	//	("->" target=[State|QNAME] // (source=[State|QNAME] '->' target=[State|QNAME] | target=[State|QNAME] '<-' source=[State|QNAME])
	//	| target=[State|QNAME] "<-") ("on" event=Event)? ("if" condition=Condition)? ("do" action=Action)? ";";
	public TransitionElements getTransitionAccess() {
		return (pTransition != null) ? pTransition : (pTransition = new TransitionElements());
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}

	//InternalTransition:
	//	("on" event=Event)? ("if" condition=Condition)? "do" action=Action ";";
	public InternalTransitionElements getInternalTransitionAccess() {
		return (pInternalTransition != null) ? pInternalTransition : (pInternalTransition = new InternalTransitionElements());
	}
	
	public ParserRule getInternalTransitionRule() {
		return getInternalTransitionAccess().getRule();
	}

	//Event:
	//	SymbolicEvent | TransitionEvent | EnterEvent | ExitEvent | ScriptEvent | TimerEvent;
	public EventElements getEventAccess() {
		return (pEvent != null) ? pEvent : (pEvent = new EventElements());
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}

	//SymbolicEvent:
	//	name=ID "!";
	public SymbolicEventElements getSymbolicEventAccess() {
		return (pSymbolicEvent != null) ? pSymbolicEvent : (pSymbolicEvent = new SymbolicEventElements());
	}
	
	public ParserRule getSymbolicEventRule() {
		return getSymbolicEventAccess().getRule();
	}

	//TransitionEvent:
	//	(source=[State|QNAME] "->" target=[State|QNAME] | target=[State|QNAME] "<-" source=[State|QNAME]) | ("->"
	//	target=[State|QNAME] // implicit EnterEvent
	//	| target=[State|QNAME] "<-") | (source=[State|QNAME] "->" // implicit ExitEvent
	//	| "<-" source=[State|QNAME]);
	public TransitionEventElements getTransitionEventAccess() {
		return (pTransitionEvent != null) ? pTransitionEvent : (pTransitionEvent = new TransitionEventElements());
	}
	
	public ParserRule getTransitionEventRule() {
		return getTransitionEventAccess().getRule();
	}

	//EnterEvent:
	//	{EnterEvent} "enter";
	public EnterEventElements getEnterEventAccess() {
		return (pEnterEvent != null) ? pEnterEvent : (pEnterEvent = new EnterEventElements());
	}
	
	public ParserRule getEnterEventRule() {
		return getEnterEventAccess().getRule();
	}

	//ExitEvent:
	//	{ExitEvent} "exit";
	public ExitEventElements getExitEventAccess() {
		return (pExitEvent != null) ? pExitEvent : (pExitEvent = new ExitEventElements());
	}
	
	public ParserRule getExitEventRule() {
		return getExitEventAccess().getRule();
	}

	//ScriptEvent:
	//	script=SCRIPT_EXPRESSION;
	public ScriptEventElements getScriptEventAccess() {
		return (pScriptEvent != null) ? pScriptEvent : (pScriptEvent = new ScriptEventElements());
	}
	
	public ParserRule getScriptEventRule() {
		return getScriptEventAccess().getRule();
	}

	//TimerEvent:
	//	"t" ">" delay=Expression "after" event=Event;
	public TimerEventElements getTimerEventAccess() {
		return (pTimerEvent != null) ? pTimerEvent : (pTimerEvent = new TimerEventElements());
	}
	
	public ParserRule getTimerEventRule() {
		return getTimerEventAccess().getRule();
	}

	//Condition:
	//	script=SCRIPT_EXPRESSION;
	public ConditionElements getConditionAccess() {
		return (pCondition != null) ? pCondition : (pCondition = new ConditionElements());
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}

	//Action:
	//	SymbolicAction | ScriptAction | AssignmentAction;
	public ActionElements getActionAccess() {
		return (pAction != null) ? pAction : (pAction = new ActionElements());
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}

	//SymbolicAction:
	//	name=ID ("after" delay=Expression)? "!";
	public SymbolicActionElements getSymbolicActionAccess() {
		return (pSymbolicAction != null) ? pSymbolicAction : (pSymbolicAction = new SymbolicActionElements());
	}
	
	public ParserRule getSymbolicActionRule() {
		return getSymbolicActionAccess().getRule();
	}

	//ScriptAction:
	//	script=SCRIPT_STATEMENTS;
	public ScriptActionElements getScriptActionAccess() {
		return (pScriptAction != null) ? pScriptAction : (pScriptAction = new ScriptActionElements());
	}
	
	public ParserRule getScriptActionRule() {
		return getScriptActionAccess().getRule();
	}

	//VarDef:
	//	"var" name=ID (":" eType=[ecore::EClassifier|QNAME] many?=("*" | "[]")?)? ("=" init=Expression)? ";";
	public VarDefElements getVarDefAccess() {
		return (pVarDef != null) ? pVarDef : (pVarDef = new VarDefElements());
	}
	
	public ParserRule getVarDefRule() {
		return getVarDefAccess().getRule();
	}

	//AssignmentAction:
	//	var=[VarDef|QNAME] "=" value=Expression;
	public AssignmentActionElements getAssignmentActionAccess() {
		return (pAssignmentAction != null) ? pAssignmentAction : (pAssignmentAction = new AssignmentActionElements());
	}
	
	public ParserRule getAssignmentActionRule() {
		return getAssignmentActionAccess().getRule();
	}

	//// Expression part of the grammar
	//terminal SCRIPT_EXPRESSION:
	//	"[["->"]]";
	public TerminalRule getSCRIPT_EXPRESSIONRule() {
		return (tSCRIPT_EXPRESSION != null) ? tSCRIPT_EXPRESSION : (tSCRIPT_EXPRESSION = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SCRIPT_EXPRESSION"));
	} 

	//terminal SCRIPT_STATEMENTS:
	//	"{{"->"}}";
	public TerminalRule getSCRIPT_STATEMENTSRule() {
		return (tSCRIPT_STATEMENTS != null) ? tSCRIPT_STATEMENTS : (tSCRIPT_STATEMENTS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SCRIPT_STATEMENTS"));
	} 

	//terminal URI_LITERAL returns EURI:
	//	"@" ("a".."z" | "A".."Z" | "0".."9" | ":" | "_" | "-" | "+" | "." | "/" | "#" | "?" | "=" | "&" | "%" | "@" | "$")+;
	public TerminalRule getURI_LITERALRule() {
		return (tURI_LITERAL != null) ? tURI_LITERAL : (tURI_LITERAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "URI_LITERAL"));
	} 

	//terminal EOBJECT_URI_LITERAL returns EURI:
	//	"Û" ("a".."z" | "A".."Z" | "0".."9" | ":" | "_" | "-" | "+" | "." | "/" | "#" | "?" | "=" | "&" | "%" | "@" | "$")+;
	public TerminalRule getEOBJECT_URI_LITERALRule() {
		return (tEOBJECT_URI_LITERAL != null) ? tEOBJECT_URI_LITERAL : (tEOBJECT_URI_LITERAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "EOBJECT_URI_LITERAL"));
	} 

	//BOOLEAN_LITERAL returns ecore::EBoolean:
	//	"true" | "false";
	public BOOLEAN_LITERALElements getBOOLEAN_LITERALAccess() {
		return (pBOOLEAN_LITERAL != null) ? pBOOLEAN_LITERAL : (pBOOLEAN_LITERAL = new BOOLEAN_LITERALElements());
	}
	
	public ParserRule getBOOLEAN_LITERALRule() {
		return getBOOLEAN_LITERALAccess().getRule();
	}

	//FLOAT_LITERAL returns ecore::EDouble:
	//	(INT | POS_INT | NEG_INT) "." INT;
	public FLOAT_LITERALElements getFLOAT_LITERALAccess() {
		return (pFLOAT_LITERAL != null) ? pFLOAT_LITERAL : (pFLOAT_LITERAL = new FLOAT_LITERALElements());
	}
	
	public ParserRule getFLOAT_LITERALRule() {
		return getFLOAT_LITERALAccess().getRule();
	}

	//POS_INT returns ecore::EInt:
	//	"+" INT;
	public POS_INTElements getPOS_INTAccess() {
		return (pPOS_INT != null) ? pPOS_INT : (pPOS_INT = new POS_INTElements());
	}
	
	public ParserRule getPOS_INTRule() {
		return getPOS_INTAccess().getRule();
	}

	//NEG_INT returns ecore::EInt:
	//	"-" INT;
	public NEG_INTElements getNEG_INTAccess() {
		return (pNEG_INT != null) ? pNEG_INT : (pNEG_INT = new NEG_INTElements());
	}
	
	public ParserRule getNEG_INTRule() {
		return getNEG_INTAccess().getRule();
	}

	//QNAME returns ecore::EString:
	//	ID ("." ID)*;
	public QNAMEElements getQNAMEAccess() {
		return (pQNAME != null) ? pQNAME : (pQNAME = new QNAMEElements());
	}
	
	public ParserRule getQNAMERule() {
		return getQNAMEAccess().getRule();
	}

	//Expression:
	//	Literal | ScriptExpression | EPath;
	public ExpressionElements getExpressionAccess() {
		return (pExpression != null) ? pExpression : (pExpression = new ExpressionElements());
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}

	//Literal:
	//	BooleanLiteral | FloatLiteral | IntLiteral | StringLiteral | UriLiteral | EObjectUriLiteral | DelayLiteral;
	public LiteralElements getLiteralAccess() {
		return (pLiteral != null) ? pLiteral : (pLiteral = new LiteralElements());
	}
	
	public ParserRule getLiteralRule() {
		return getLiteralAccess().getRule();
	}

	//BooleanLiteral:
	//	booleanValue=BOOLEAN_LITERAL;
	public BooleanLiteralElements getBooleanLiteralAccess() {
		return (pBooleanLiteral != null) ? pBooleanLiteral : (pBooleanLiteral = new BooleanLiteralElements());
	}
	
	public ParserRule getBooleanLiteralRule() {
		return getBooleanLiteralAccess().getRule();
	}

	//IntLiteral:
	//	intValue=(INT | POS_INT | NEG_INT);
	public IntLiteralElements getIntLiteralAccess() {
		return (pIntLiteral != null) ? pIntLiteral : (pIntLiteral = new IntLiteralElements());
	}
	
	public ParserRule getIntLiteralRule() {
		return getIntLiteralAccess().getRule();
	}

	//FloatLiteral:
	//	floatValue=FLOAT_LITERAL;
	public FloatLiteralElements getFloatLiteralAccess() {
		return (pFloatLiteral != null) ? pFloatLiteral : (pFloatLiteral = new FloatLiteralElements());
	}
	
	public ParserRule getFloatLiteralRule() {
		return getFloatLiteralAccess().getRule();
	}

	//StringLiteral:
	//	stringValue=STRING;
	public StringLiteralElements getStringLiteralAccess() {
		return (pStringLiteral != null) ? pStringLiteral : (pStringLiteral = new StringLiteralElements());
	}
	
	public ParserRule getStringLiteralRule() {
		return getStringLiteralAccess().getRule();
	}

	//UriLiteral:
	//	uri=URI_LITERAL;
	public UriLiteralElements getUriLiteralAccess() {
		return (pUriLiteral != null) ? pUriLiteral : (pUriLiteral = new UriLiteralElements());
	}
	
	public ParserRule getUriLiteralRule() {
		return getUriLiteralAccess().getRule();
	}

	//EObjectUriLiteral:
	//	uri=EOBJECT_URI_LITERAL;
	public EObjectUriLiteralElements getEObjectUriLiteralAccess() {
		return (pEObjectUriLiteral != null) ? pEObjectUriLiteral : (pEObjectUriLiteral = new EObjectUriLiteralElements());
	}
	
	public ParserRule getEObjectUriLiteralRule() {
		return getEObjectUriLiteralAccess().getRule();
	}

	//enum TimeUnit:
	//	ms | s | m | h;
	public TimeUnitElements getTimeUnitAccess() {
		return (unknownRuleTimeUnit != null) ? unknownRuleTimeUnit : (unknownRuleTimeUnit = new TimeUnitElements());
	}
	
	public EnumRule getTimeUnitRule() {
		return getTimeUnitAccess().getRule();
	}

	//DelayLiteral:
	//	intValue=INT timeUnit=TimeUnit;
	public DelayLiteralElements getDelayLiteralAccess() {
		return (pDelayLiteral != null) ? pDelayLiteral : (pDelayLiteral = new DelayLiteralElements());
	}
	
	public ParserRule getDelayLiteralRule() {
		return getDelayLiteralAccess().getRule();
	}

	//VarRef:
	//	var=[VarDef|QNAME];
	public VarRefElements getVarRefAccess() {
		return (pVarRef != null) ? pVarRef : (pVarRef = new VarRefElements());
	}
	
	public ParserRule getVarRefRule() {
		return getVarRefAccess().getRule();
	}

	//EPath:
	//	var=VarRef steps+=EStep*;
	public EPathElements getEPathAccess() {
		return (pEPath != null) ? pEPath : (pEPath = new EPathElements());
	}
	
	public ParserRule getEPathRule() {
		return getEPathAccess().getRule();
	}

	//EStep:
	//	"/ " featureName=ID filter=EStepFilter?;
	public EStepElements getEStepAccess() {
		return (pEStep != null) ? pEStep : (pEStep = new EStepElements());
	}
	
	public ParserRule getEStepRule() {
		return getEStepAccess().getRule();
	}

	//EStepFilter:
	//	script=ScriptExpression;
	public EStepFilterElements getEStepFilterAccess() {
		return (pEStepFilter != null) ? pEStepFilter : (pEStepFilter = new EStepFilterElements());
	}
	
	public ParserRule getEStepFilterRule() {
		return getEStepFilterAccess().getRule();
	}

	//ScriptExpression:
	//	script=SCRIPT_EXPRESSION;
	public ScriptExpressionElements getScriptExpressionAccess() {
		return (pScriptExpression != null) ? pScriptExpression : (pScriptExpression = new ScriptExpressionElements());
	}
	
	public ParserRule getScriptExpressionRule() {
		return getScriptExpressionAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" | "n" |
	//	"f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
