/*
* generated by Xtext
*/
package no.hal.scxml.ui.contentassist;

import no.hal.scxml.ui.contentassist.AbstractScxmlxtProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ScxmlxtProposalProvider extends AbstractScxmlxtProposalProvider {

}
