/*
* generated by Xtext
*/
package no.hal.scxml.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class ScxmlxtTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
